### ISSUE TITLE
BUG: Ansible Automation Script not creating Symbolic Link to enable the site.

### ISSUE THREAD

**Issue by thisisayush** [vipulgupta2048/scrape#68]
Ansible Handler "acivate nginx site" is not creating a symbolic link which will enable the Nginx site.
```
- name: activate nginx site
  file:
    src: /etc/nginx/sites-available/scraper
    dest: /etc/nginx/sites-enabled/scraper
    state: link
  notify:
    - restart nginx
```
